# Uncomment the next line to define a global platform for your project
platform :ios, '13.1.3'

target 'connectedtravel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for connectedtravel
  pod 'SmartDeviceLink', '~> 6.2'

  target 'connectedtravelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'connectedtravelUITests' do
    # Pods for testing
  end

end
