# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartDeviceLink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartDeviceLink

  target 'SmartDeviceLinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SmartDeviceLink-Example-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartDeviceLink-Example-ObjC

end

target 'SmartDeviceLink-Example-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartDeviceLink-Example-Swift

end

target 'SmartDeviceLinkSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartDeviceLinkSwift

end
