# Generated by Django 2.2.7 on 2019-11-15 03:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=100)),
                ('artists', models.ManyToManyField(to='mainapp.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bit_link', models.URLField()),
                ('tm_link', models.URLField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date', models.DateTimeField()),
                ('pref_link', models.IntegerField()),
                ('artists', models.ManyToManyField(to='mainapp.Artist')),
            ],
        ),
    ]
